/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSplatRouteImport } from './routes/blog/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppEscalationsRouteImport } from './routes/_app/escalations'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as ApiCronProcessEmailsRouteImport } from './routes/api/cron/process-emails'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppPaymentIdRouteImport } from './routes/_app/payment.$id'
import { Route as ApiWebhooksStripeIndexRouteImport } from './routes/api/webhooks/stripe/index'
import { Route as ApiStripeConnectFallbackRouteImport } from './routes/api/stripe/connect/fallback'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSplatRoute = BlogSplatRouteImport.update({
  id: '/blog/$',
  path: '/blog/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppEscalationsRoute = AppEscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const ApiCronProcessEmailsRoute = ApiCronProcessEmailsRouteImport.update({
  id: '/api/cron/process-emails',
  path: '/api/cron/process-emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPaymentIdRoute = AppPaymentIdRouteImport.update({
  id: '/payment/$id',
  path: '/payment/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiWebhooksStripeIndexRoute = ApiWebhooksStripeIndexRouteImport.update({
  id: '/api/webhooks/stripe/',
  path: '/api/webhooks/stripe/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeConnectFallbackRoute =
  ApiStripeConnectFallbackRouteImport.update({
    id: '/api/stripe/connect/fallback',
    path: '/api/stripe/connect/fallback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/escalations': typeof AppEscalationsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/settings': typeof AppSettingsRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$': typeof BlogSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/payment/$id': typeof AppPaymentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/process-emails': typeof ApiCronProcessEmailsRoute
  '/api/stripe/connect/fallback': typeof ApiStripeConnectFallbackRoute
  '/api/webhooks/stripe/': typeof ApiWebhooksStripeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AppDashboardRoute
  '/escalations': typeof AppEscalationsRoute
  '/onboarding': typeof AppOnboardingRoute
  '/settings': typeof AppSettingsRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$': typeof BlogSplatRoute
  '/blog': typeof BlogIndexRoute
  '/payment/$id': typeof AppPaymentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/process-emails': typeof ApiCronProcessEmailsRoute
  '/api/stripe/connect/fallback': typeof ApiStripeConnectFallbackRoute
  '/api/webhooks/stripe': typeof ApiWebhooksStripeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/escalations': typeof AppEscalationsRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/search': typeof ApiSearchRoute
  '/blog/$': typeof BlogSplatRoute
  '/blog/': typeof BlogIndexRoute
  '/_app/payment/$id': typeof AppPaymentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cron/process-emails': typeof ApiCronProcessEmailsRoute
  '/api/stripe/connect/fallback': typeof ApiStripeConnectFallbackRoute
  '/api/webhooks/stripe/': typeof ApiWebhooksStripeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/escalations'
    | '/onboarding'
    | '/settings'
    | '/api/search'
    | '/blog/$'
    | '/blog/'
    | '/payment/$id'
    | '/api/auth/$'
    | '/api/cron/process-emails'
    | '/api/stripe/connect/fallback'
    | '/api/webhooks/stripe/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/escalations'
    | '/onboarding'
    | '/settings'
    | '/api/search'
    | '/blog/$'
    | '/blog'
    | '/payment/$id'
    | '/api/auth/$'
    | '/api/cron/process-emails'
    | '/api/stripe/connect/fallback'
    | '/api/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/dashboard'
    | '/_app/escalations'
    | '/_app/onboarding'
    | '/_app/settings'
    | '/api/search'
    | '/blog/$'
    | '/blog/'
    | '/_app/payment/$id'
    | '/api/auth/$'
    | '/api/cron/process-emails'
    | '/api/stripe/connect/fallback'
    | '/api/webhooks/stripe/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiSearchRoute: typeof ApiSearchRoute
  BlogSplatRoute: typeof BlogSplatRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCronProcessEmailsRoute: typeof ApiCronProcessEmailsRoute
  ApiStripeConnectFallbackRoute: typeof ApiStripeConnectFallbackRoute
  ApiWebhooksStripeIndexRoute: typeof ApiWebhooksStripeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$': {
      id: '/blog/$'
      path: '/blog/$'
      fullPath: '/blog/$'
      preLoaderRoute: typeof BlogSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/escalations': {
      id: '/_app/escalations'
      path: '/escalations'
      fullPath: '/escalations'
      preLoaderRoute: typeof AppEscalationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/cron/process-emails': {
      id: '/api/cron/process-emails'
      path: '/api/cron/process-emails'
      fullPath: '/api/cron/process-emails'
      preLoaderRoute: typeof ApiCronProcessEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/payment/$id': {
      id: '/_app/payment/$id'
      path: '/payment/$id'
      fullPath: '/payment/$id'
      preLoaderRoute: typeof AppPaymentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/webhooks/stripe/': {
      id: '/api/webhooks/stripe/'
      path: '/api/webhooks/stripe'
      fullPath: '/api/webhooks/stripe/'
      preLoaderRoute: typeof ApiWebhooksStripeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/connect/fallback': {
      id: '/api/stripe/connect/fallback'
      path: '/api/stripe/connect/fallback'
      fullPath: '/api/stripe/connect/fallback'
      preLoaderRoute: typeof ApiStripeConnectFallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppEscalationsRoute: typeof AppEscalationsRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppPaymentIdRoute: typeof AppPaymentIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppEscalationsRoute: AppEscalationsRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppPaymentIdRoute: AppPaymentIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiSearchRoute: ApiSearchRoute,
  BlogSplatRoute: BlogSplatRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCronProcessEmailsRoute: ApiCronProcessEmailsRoute,
  ApiStripeConnectFallbackRoute: ApiStripeConnectFallbackRoute,
  ApiWebhooksStripeIndexRoute: ApiWebhooksStripeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
